# Generated by Django 5.1.2 on 2024-12-04 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('M', 'Мужская'), ('F', 'Женская')], default='M', max_length=1),
        ),
    ]
